version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "go"
    ignore:
      - dependency-name: "k8s.io/*"
        versions: ["<1.26.0"]
