apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.fullname" . }}-controller-manager-metrics-service
  labels:
    control-plane: controller-manager
  {{- include "charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    app.kubernetes.io/name: openstack-lb-operator
    control-plane: controller-manager
    {{- include "charts.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.metricsService.ports | toYaml | nindent 2 }}
