# This rule is not used by the project openstack-lb-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the openstack.jacero.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: openstack-lb-operator
    app.kubernetes.io/managed-by: kustomize
  name: openstackloadbalancer-editor-role
rules:
- apiGroups:
  - openstack.jacero.io
  resources:
  - openstackloadbalancers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.jacero.io
  resources:
  - openstackloadbalancers/status
  verbs:
  - get
