controllerManager:
  manager:
    args:
    - --metrics-bind-address=:8443
    - --leader-elect
    - --health-probe-bind-address=:8081
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    env:
      openstackCaCertPath: /etc/ssl/certs/openstack-ca
    image:
      repository: ghcr.io/jacero-io/openstack-lb-operator
      tag: v0.0.0-latest
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  replicas: 1
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  type: ClusterIP
# CA Certificates configuration
caCerts:
  # Set to false by default - users can enable when needed
  enabled: false
  # Source can be 'configMap' or 'secret'
  source: configMap
  # Name of the configMap or secret
  name: openstack-ca-certs
  # Mount path - the controller will scan this directory for certificate files
  mountPath: /etc/ssl/certs/openstack-ca
  # Individual certificate files or a bundle of certificates
  items:
    # Default empty to mount all keys from the configMap/secret
    {}
    # If you want to explicitly map specific keys to files, use this format:
    # ca1.crt: company-ca.crt
    # ca2.crt: department-ca.crt