apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- service.yaml
- openstack_v1alpha1_openstackloadbalancer.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
