---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
spec:
  loadBalancerClass: "metallb" 
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx2
  namespace: default
spec:
  loadBalancerClass: "metallb" 
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
