name: Build & Publish Container Images to GHCR

on:
  push:
    branches:
      - main
      - 'feature/*'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    env:
      PLATFORMS: linux/arm64,linux/amd64,linux/s390x,linux/ppc64le
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        env:
          DESCRIPTION: OpenStack Load Balancer Operator is a Kubernetes operator that integrates Kubernetes service load balancers with OpenStack networking.
        with:
          images: ghcr.io/${{ github.repository_owner }}/openstack-lb-operator
          tags: |
            type=semver,pattern=v{{version}},event=tag
            type=semver,pattern=v{{major}}.{{minor}},event=tag
            type=semver,pattern=v{{major}},event=tag
            type=ref,event=pr
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=dev-latest
          labels: |
            org.opencontainers.image.authors=maintainers@jacero.io
            org.opencontainers.image.description=${{ env.DESCRIPTION }}
          annotations: |
            org.opencontainers.image.authors=maintainers@jacero.io
            org.opencontainers.image.description=${{ env.DESCRIPTION }}

      - name: Log in to GitHub Container Registry
        if: (github.event_name != 'pull_request' || github.event.pull_request.head_repository.full_name == github.repository) && github.actor != 'dependabot[bot]'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' || github.event.pull_request.head_repository.full_name == github.repository }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
